project_id = "dgwmwmofyaxstykwuzxh"

[functions.create-user]
verify_jwt = false

[functions.manage-user]
verify_jwt = false

[functions.sync-sales-data]
verify_jwt = true

[functions.sync-pipefy-funnel]
verify_jwt = false
